str(DATARSU)   
DATARSU <- as.factor(DATARSU)
DATARSU <- as.factor(municipio)
DATARSU$Municipio <- as.factor(DATARSU$Municipio)
plot(DATARSU)
install.packages("fBasics")
table(DATARSU$Populacao)
prop.table(table(DATARSU$Populacao))
mean(DATARSU$Populacao)
median(DATARSU$Populacao)
quantile(DATARSU$Populacao, probs = 0.75)
quantile(DATARSU$Populacao, probs = 0.95)
boxplot(DATARSU$Populacao)
sd(DATARSU$Populacao)
plot(DATARSU$Populacao)
summary(DATARSU)
summary(DATARSU)

boxplot(DATARSU$Populacao)
sd(DATARSU$Populacao)

summary(DATARSU)
DATARSU <- as.factor(DATARSU)
mean(DATARSU)
mean(DATARSU)
DATARSU$Municipio <- as.factor(DATARSU$Municipio)
mean(DATARSU$Municipio)
